global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'event-service'
    static_configs:
      - targets: ['event-service:8080']

  - job_name: 'question-service'
    static_configs:
      - targets: ['question-service:8080']

  - job_name: 'moderation-service'
    static_configs:
      - targets: ['moderation-service:8080']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8080']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8080']
